language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
on:
  branch: master
